export const GET_MANAGE_PAGE_ARTICLE_LIST_DATA = 'getManagePageArticleListData'

export const TRIGGER_ISLOADING_MANAGE_PAGE_ARTICLE_LIST_DATA = 'triggerIsloadingManagePageArticleListData'

export const GET_MANAGE_PAGE_ARTICLE_FILING_DATA = 'getManagePageArticleFilingData'

export const GET_MANAGE_PAGE_ARTICLE_LABEL_DATA = 'getManagePageArticleLabelData'

export const GET_MANAGE_PAGE_ARTICLE_LIST_DATA_BY_KEY_WORD = 'getManagePageArticleListDataByKeyWord'

export const REFRESH_MANAGE_PAGE_PAGINATION = 'refreshManagePagePagination'

export const GET_MANAGE_PAGE_ARTICLE_LIST_DATA_BY_FILING = 'getManagePageArticleListDataByFiling'