export const GET_MANAGE_PAGE_ARTICLE_LIST_DATA = 'getManagePageArticleListData'

export const TRIGGER_ISLOADING_MANAGE_PAGE_ARTICLE_LIST_DATA = 'triggerIsloadingManagePageArticleListData'

export const GET_MANAGE_PAGE_ARTICLE_FILING_DATA = 'getManagePageArticleFilingData'

export const GET_MANAGE_PAGE_ARTICLE_LABEL_DATA = 'getManagePageArticleLabelData'

export const GET_MANAGE_PAGE_ARTICLE_LIST_DATA_BY_KEY_WORD = 'getManagePageArticleListDataByKeyWord'

export const APPOINT_MANAGE_PAGE_PAGINATION = 'appointManagePagePagination'

export const GET_MANAGE_PAGE_ARTICLE_LIST_DATA_BY_FILING = 'getManagePageArticleListDataByFiling'

export const GET_MANAGE_PAGE_ARTICLE_LIST_DATA_BY_LABEL = 'getManagePageArticleListDataByLabel'

export const RESET_CENTRAL_CONTROLLER_OF_MANAGE_PAGE = 'resetCentralControllerOfManagePage'

export const TRIGGER_IS_MULTIPLE_SELECTING_IN_MANAGE_PAGE = 'triggerIsMultipleSelectingInManagePage'

export const DELETE_ARTICLE_LIST = 'deleteArticleList'